### ISSUE TITLE
cron実装する

### ISSUE THREAD

**Issue by kyokomi** [kyokomi/nepu-bot#12]
hubot cronのパクリでいいかと思ったけど。なんか色々難しい

https://github.com/kyokomi/slackbot/blob/master/plugins/cron/cron.go

**Comment by kyokomi** [comment]
- [ ] cron設定の登録依頼を投げたらredisに保存とcronを起動
- [ ] 起動時にredisを読み込んでcron登録
- [ ] cron設定の削除依頼を投げたらredisから削除してcronを停止
- [ ] 管理画面で登録中のcron設定を一覧表示
- [ ] cron設定をしゃべるやつも実装する

**Comment by dmnlk** [comment]
cron_idでlist/delete

**Comment by kyokomi** [comment]
thx!
